建议跳过可用tg
Moonlark-Dev/Moonlark pull request #179
Opened 2024-08-18 10:00 UTC by HOStudio123

适用打键盘比较慢，太紧张想不到英文的人群

2024-08-18 10:00 UTC, pep8speaks commented
Hello @HOStudio123! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`src/plugins/nonebot_plugin_quick_math/commands/main.py`](https://github.com/Moonlark-Dev/Moonlark/blob/c88614792fd5aa298b2bfb64eef8c0e336b2dc8a/src/plugins/nonebot_plugin_quick_math/commands/main.py):

> [Line 37:13](https://github.com/Moonlark-Dev/Moonlark/blob/c88614792fd5aa298b2bfb64eef8c0e336b2dc8a/src/plugins/nonebot_plugin_quick_math/commands/main.py#L37): [W503](https://duckduckgo.com/?q=pep8%20W503) line break before binary operator

2024-08-18 10:05 UTC, chun-awa approved these changes

2024-08-18 12:41 UTC, HOStudio123 commented
@This-is-XiaoDeng

2024-08-18 12:46 UTC, This-is-XiaoDeng requested changes

2024-08-18 12:46 UTC, This-is-XiaoDeng commented on src/plugins/nonebot_plugin_quick_math/commands/main.py
> +            or ((message.lower() == "skip" or message.lower() == "tg") and total_skipping_count > skipped_question)
这里建议用 in 比较好看点，可以在 config 加一个 `quickmath_skip_keyword` 配置

2024-08-18 13:11 UTC, HOStudio123 commented on src/plugins/nonebot_plugin_quick_math/commands/main.py
> +            or ((message.lower() == "skip" or message.lower() == "tg") and total_skipping_count > skipped_question)
```suggestion
            or (message.lower() in  ['"skip", "tg"] and total_skipping_count > skipped_question)
```

2024-08-18 13:11 UTC, HOStudio123 commented on src/plugins/nonebot_plugin_quick_math/commands/main.py
> +        elif resp.extract_plain_text().lower() == "skip" or resp.extract_plain_text().lower() == "tg":
```suggestion
        elif resp.extract_plain_text().lower() == ["skip", "tg"]:
```

2024-08-18 14:42 UTC, This-is-XiaoDeng commented
直接改

2024-08-18 22:24 UTC, HOStudio123 commented
> 直接改

改了

2024-08-19 06:02 UTC, This-is-XiaoDeng approved these changes
但还是建议使用 [`plugin_config`][1] 设置可用的关键字，谢谢

[1]: https://nonebot.dev/docs/appendices/config#%E6%8F%92%E4%BB%B6%E9%85%8D%E7%BD%AE

2024-08-19 06:03 UTC, merged

2024-08-19 10:25 UTC, HOStudio123 commented
> 但还是建议使用 [`plugin_config`](https://nonebot.dev/docs/appendices/config#%E6%8F%92%E4%BB%B6%E9%85%8D%E7%BD%AE) 设置可用的关键字，谢谢

下次一定，等我研究研究