Create bronya.md
Moonlark-Dev/Moonlark pull request #214
Opened 2024-08-29 14:46 UTC by zhao6888

xd怕被审核骂所以我发

- [ ] 此 Pull Requests 进行的更改已经过测试

### 有关问题链接

Fixes #

### 描述

2024-08-29 14:48 UTC, This-is-XiaoDeng requested changes
哪有 MarkDown 这么写的啊（

2024-08-29 15:20 UTC, pep8speaks commented
Hello @zhao6888! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`bronya.py`](https://github.com/Moonlark-Dev/Moonlark/blob/4173fe7ec919044835d0f81278ac1f300eb702f9/bronya.py):

> [Line 2:1](https://github.com/Moonlark-Dev/Moonlark/blob/4173fe7ec919044835d0f81278ac1f300eb702f9/bronya.py#L2): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 3:1](https://github.com/Moonlark-Dev/Moonlark/blob/4173fe7ec919044835d0f81278ac1f300eb702f9/bronya.py#L3): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 4:87](https://github.com/Moonlark-Dev/Moonlark/blob/4173fe7ec919044835d0f81278ac1f300eb702f9/bronya.py#L4): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 5:88](https://github.com/Moonlark-Dev/Moonlark/blob/4173fe7ec919044835d0f81278ac1f300eb702f9/bronya.py#L5): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 6:88](https://github.com/Moonlark-Dev/Moonlark/blob/4173fe7ec919044835d0f81278ac1f300eb702f9/bronya.py#L6): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 7:88](https://github.com/Moonlark-Dev/Moonlark/blob/4173fe7ec919044835d0f81278ac1f300eb702f9/bronya.py#L7): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 8:88](https://github.com/Moonlark-Dev/Moonlark/blob/4173fe7ec919044835d0f81278ac1f300eb702f9/bronya.py#L8): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 9:88](https://github.com/Moonlark-Dev/Moonlark/blob/4173fe7ec919044835d0f81278ac1f300eb702f9/bronya.py#L9): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 10:100](https://github.com/Moonlark-Dev/Moonlark/blob/4173fe7ec919044835d0f81278ac1f300eb702f9/bronya.py#L10): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 17:100](https://github.com/Moonlark-Dev/Moonlark/blob/4173fe7ec919044835d0f81278ac1f300eb702f9/bronya.py#L17): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 18:96](https://github.com/Moonlark-Dev/Moonlark/blob/4173fe7ec919044835d0f81278ac1f300eb702f9/bronya.py#L18): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 19:99](https://github.com/Moonlark-Dev/Moonlark/blob/4173fe7ec919044835d0f81278ac1f300eb702f9/bronya.py#L19): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 22:100](https://github.com/Moonlark-Dev/Moonlark/blob/4173fe7ec919044835d0f81278ac1f300eb702f9/bronya.py#L22): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 23:100](https://github.com/Moonlark-Dev/Moonlark/blob/4173fe7ec919044835d0f81278ac1f300eb702f9/bronya.py#L23): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 24:100](https://github.com/Moonlark-Dev/Moonlark/blob/4173fe7ec919044835d0f81278ac1f300eb702f9/bronya.py#L24): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 25:99](https://github.com/Moonlark-Dev/Moonlark/blob/4173fe7ec919044835d0f81278ac1f300eb702f9/bronya.py#L25): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 26:97](https://github.com/Moonlark-Dev/Moonlark/blob/4173fe7ec919044835d0f81278ac1f300eb702f9/bronya.py#L26): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 27:95](https://github.com/Moonlark-Dev/Moonlark/blob/4173fe7ec919044835d0f81278ac1f300eb702f9/bronya.py#L27): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 28:97](https://github.com/Moonlark-Dev/Moonlark/blob/4173fe7ec919044835d0f81278ac1f300eb702f9/bronya.py#L28): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 29:96](https://github.com/Moonlark-Dev/Moonlark/blob/4173fe7ec919044835d0f81278ac1f300eb702f9/bronya.py#L29): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 30:95](https://github.com/Moonlark-Dev/Moonlark/blob/4173fe7ec919044835d0f81278ac1f300eb702f9/bronya.py#L30): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 31:95](https://github.com/Moonlark-Dev/Moonlark/blob/4173fe7ec919044835d0f81278ac1f300eb702f9/bronya.py#L31): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 32:94](https://github.com/Moonlark-Dev/Moonlark/blob/4173fe7ec919044835d0f81278ac1f300eb702f9/bronya.py#L32): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 33:94](https://github.com/Moonlark-Dev/Moonlark/blob/4173fe7ec919044835d0f81278ac1f300eb702f9/bronya.py#L33): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 34:94](https://github.com/Moonlark-Dev/Moonlark/blob/4173fe7ec919044835d0f81278ac1f300eb702f9/bronya.py#L34): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 35:94](https://github.com/Moonlark-Dev/Moonlark/blob/4173fe7ec919044835d0f81278ac1f300eb702f9/bronya.py#L35): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 36:90](https://github.com/Moonlark-Dev/Moonlark/blob/4173fe7ec919044835d0f81278ac1f300eb702f9/bronya.py#L36): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 37:91](https://github.com/Moonlark-Dev/Moonlark/blob/4173fe7ec919044835d0f81278ac1f300eb702f9/bronya.py#L37): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 38:91](https://github.com/Moonlark-Dev/Moonlark/blob/4173fe7ec919044835d0f81278ac1f300eb702f9/bronya.py#L38): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 39:90](https://github.com/Moonlark-Dev/Moonlark/blob/4173fe7ec919044835d0f81278ac1f300eb702f9/bronya.py#L39): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 40:86](https://github.com/Moonlark-Dev/Moonlark/blob/4173fe7ec919044835d0f81278ac1f300eb702f9/bronya.py#L40): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 41:80](https://github.com/Moonlark-Dev/Moonlark/blob/4173fe7ec919044835d0f81278ac1f300eb702f9/bronya.py#L41): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 42:78](https://github.com/Moonlark-Dev/Moonlark/blob/4173fe7ec919044835d0f81278ac1f300eb702f9/bronya.py#L42): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 43:63](https://github.com/Moonlark-Dev/Moonlark/blob/4173fe7ec919044835d0f81278ac1f300eb702f9/bronya.py#L43): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 44:63](https://github.com/Moonlark-Dev/Moonlark/blob/4173fe7ec919044835d0f81278ac1f300eb702f9/bronya.py#L44): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 45:60](https://github.com/Moonlark-Dev/Moonlark/blob/4173fe7ec919044835d0f81278ac1f300eb702f9/bronya.py#L45): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 46:56](https://github.com/Moonlark-Dev/Moonlark/blob/4173fe7ec919044835d0f81278ac1f300eb702f9/bronya.py#L46): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 47:1](https://github.com/Moonlark-Dev/Moonlark/blob/4173fe7ec919044835d0f81278ac1f300eb702f9/bronya.py#L47): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 48:1](https://github.com/Moonlark-Dev/Moonlark/blob/4173fe7ec919044835d0f81278ac1f300eb702f9/bronya.py#L48): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 49:1](https://github.com/Moonlark-Dev/Moonlark/blob/4173fe7ec919044835d0f81278ac1f300eb702f9/bronya.py#L49): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2024-08-30 03:25 UTC, chun-awa requested changes
给我改回md

2024-08-30 04:24 UTC, This-is-XiaoDeng requested changes
用 txt

2024-08-31 02:27 UTC, merged