Fix #232
Moonlark-Dev/Moonlark pull request #243
Opened 2024-10-05 12:32 UTC by LzzKill

- [ ] 此 Pull Requests 进行的更改已经过测试

### 有关问题链接

Fixes #232 

### 描述

2024-10-05 12:56 UTC, chun-awa requested changes
¿

2024-10-05 16:53 UTC, This-is-XiaoDeng commented
> - [ ] 此 Pull Requests 进行的更改已经过测试
> 
> ### 有关问题链接
> 
> Fixes #
> 
> ### 描述
> 
> 

请认真填写 PR 的主体模板谢谢

2024-10-05 17:06 UTC, This-is-XiaoDeng requested changes
总结起来有以下几个问题：

1. 你的一部分英语语法可能有点问题，可以直接用中文
2. finish 后会触发一个 finishedexception，后面的代码都执行不到
3. 除了 bag 那几个，玩法中的一些 exception 会用来传递信息而不是单纯结束处理，可以不加日志（如 Quited）
4. 你有几个 f-string 没有加花括号

2024-10-05 17:06 UTC, This-is-XiaoDeng commented on src/plugins/nonebot_plugin_bag/commands/overflow/show.py
> +        logger.warning(f"User {user_id}'s overflow show isn't found.  {traceback.format_exc()}")
这段英文怎么读起来怪怪的

2024-10-05 17:06 UTC, This-is-XiaoDeng commented on src/plugins/nonebot_plugin_bag/utils/show.py
> +        logger.warning(traceback.format_exc())
`lang.finish` 不会返回，这行代码永远不会执行到

2024-10-05 17:06 UTC, This-is-XiaoDeng commented on src/plugins/nonebot_plugin_bag/utils/tidy.py
> +        logger.warning(traceback.format_exc())
此处同上

2024-10-05 17:06 UTC, This-is-XiaoDeng commented on src/plugins/nonebot_plugin_bots/__main__.py
> +        logger.warning(traceback.format_exc())
这里不建议加，因为会导致日志特别多。

本质上这个 try 是暴力过滤掉所有不能分配的事件，如心跳等，这些事件没有 session_id。

2024-10-05 17:06 UTC, This-is-XiaoDeng commented on src/plugins/nonebot_plugin_email/web/get.py
> +        logger.warning(traceback.format_exc())
raise 后面的代码执行不到

2024-10-05 17:06 UTC, This-is-XiaoDeng commented on src/plugins/nonebot_plugin_larkcave/__main__.py
> +        logger.warning(f"User {user_id}'s cave isn't result. traceback.format_exc()")
是不是少了点什么

2024-10-05 17:06 UTC, This-is-XiaoDeng commented on src/plugins/nonebot_plugin_larkcave/__main__.py
> +        logger.warning(f"User {user_id}'s cave is undefined. traceback.format_exc()")
同上

2024-10-05 17:06 UTC, This-is-XiaoDeng commented on src/plugins/nonebot_plugin_larkcave/cool_down.py
> +        logger.warning(f"The group {group_id}'s data isn't result. traceback.format_exc()")
同上

确定 isn't result 没语法问题？

2024-10-06 03:29 UTC, chun-awa commented on src/plugins/nonebot_plugin_bag/commands/overflow/show.py
> +        logger.warning(f"User {user_id}'s overflow show isn't found.  {traceback.format_exc()}")
本来就有问题，应为`Didn't find any overflowed items in user {user_id}'s bag`

2024-10-06 04:31 UTC, This-is-XiaoDeng commented
此处存在语法错误：

```python
error: cannot format src/plugins/nonebot_plugin_larkutils/user.py: Cannot parse: 3:30: from nonebot.log import logger{logger.warning(traceback.format_exc())}
```

2024-10-06 05:12 UTC, chun-awa approved these changes

2024-10-12 15:32 UTC, This-is-XiaoDeng commented
请尽快完成更新，否则容易积合并冲突

2024-10-13 00:36 UTC, chun-awa approved these changes

2024-10-13 02:22 UTC, xxtg666 requested changes

2024-10-13 02:22 UTC, xxtg666 commented on src/plugins/nonebot_plugin_larkutils/user.py
> +from nonebot.log import logger{logger.warning(traceback.format_exc())}
```suggestion
from nonebot.log import logger
```
粘贴的时候忘记删了？

2024-10-19 14:39 UTC, This-is-XiaoDeng commented
已经出现合并冲突，建议重新更改（或使用 Diff）并重新提交。

本 Pull Request 将关闭。

2024-10-19 14:39 UTC, closed without merging