🛠️ feat: pyproject -> format settings
Moonlark-Dev/Moonlark pull request #51
Opened 2024-05-31 14:44 UTC by XieXiLin2

2024-05-31 14:54 UTC, This-is-XiaoDeng requested changes
![图片](https://github.com/Moonlark-Dev/Moonlark/assets/104149371/b5cd9e03-c071-40ac-9d07-6a7ed3406c90)

对不起，我的问题

## 人话

Moonlark 使用了 `tomllib` 这个库，但这个库从 `3.11` 才引入

所以麻烦您修改下，幸苦了

2024-05-31 14:56 UTC, XieXiLin2 reviewed
> 
![图片](https://github.com/Moonlark-Dev/Moonlark/assets/104149371/db74d486-5d8d-4c58-b5cf-5b9ae50fcb26)


对不起，我的问题

## 人话

Moonlark 使用了 `tomllib` 这个库，但这个库从 `3.11` 才引入

所以麻烦您修改下，幸苦了
 

你也是逆天的

2024-05-31 14:59 UTC, This-is-XiaoDeng approved these changes

2024-06-01 12:29 UTC, This-is-XiaoDeng commented on src/plugins/nonebot_plugin_alconna_extensions/__init__.py
> +    "@reply:ReplyMergeExtension" "src.plugins.nonebot_plugin_alconna_extensions.global_extensions:UnmatchedExtension"
```suggestion
    "@reply:ReplyMergeExtension",
    "src.plugins.nonebot_plugin_alconna_extensions.global_extensions:UnmatchedExtension"
```

2024-06-01 12:31 UTC, This-is-XiaoDeng approved these changes

2024-06-01 13:05 UTC, merged